# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c8deb26bdc56e94889a2c207fd8f8b7b41a5b086bacf1109ea76bc952541b76033c6404606c5355fa1a9b5236a14dcbce4e362739c72161ef4ce8ca49de38b

test:
  secret_key_base: ca52435b66291b6601e22f64a56213f54b3bc6ecc5cc85b9491d0e8cf695d9575079c66c845a9caf46f6bc209b22f249c5977b33aa477181f1fd0efcf5ca54ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
